# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosting',
            name='fk_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client', verbose_name='Associated Client'),
        ),
        migrations.AlterField(
            model_name='hosting',
            name='renewal_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='website',
            name='dob',
            field=models.DateField(),
        ),
    ]
