# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-14 16:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='urgency',
            new_name='urgent',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 14, 16, 52, 29, 709216, tzinfo=utc)),
        ),
    ]
