# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-14 17:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20170214_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 14, 17, 35, 43, 39056, tzinfo=utc)),
        ),
    ]
